# Generated by Django 4.1.2 on 2023-01-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
